language: c
compiler:
  - gcc
  - clang
env:
  global:
    - PREFIX=$(pwd)/install
  matrix:
    - DEBUG=0
    - DEBUG=0 MAINTAIN="--enable-maintainer-mode"
    - DEBUG=1
    - DEBUG=1 MAINTAIN="--enable-maintainer-mode"
before_script:
  - mkdir install
script:
  - ./configure --prefix=$PREFIX $MAINTAIN && make install
notifications:
  email:
    recipients:
      - craftik@cyrusian.com
    on_success: always
    on_failure: always
  irc: "irc.ozinger.org#craftIk"
